Repository GarimaSingh0109/Resum-Resume, pull requests merged in 2024-11, with the labels that each got.

#948 features: Add Forgot Password link, update title from Sign-Up to Login, and add additional social media login options in login.html and login.css.
  login.css
  login.html
Labels: level3, gssoc-ext

#1015 Header & Footer Consistency and UI Enhancement #1008
  RateMyResume.html
  about.html
  index.html
  login.css
  login.html
  resume.html
  resume_tips.html
  signup.html
Labels: level2, gssoc-ext

#820 feat: Created a responsive feedback page and linked it to navbar
  feedback.html
  feedbackformimg.jpeg
  index.html
Labels: hacktoberfest, level3, gssoc-ext, hacktoberfest-accepted

#1012 added language translation tool to all the pages
  RateMyResume.html
  about.html
  index.html
  privacy-policy.html
  resume.html
Labels: level3, gssoc-ext

#1013 Added newsletter subscription section
  index.html
Labels: level3, gssoc-ext

#1018 Navbar
  index.html
Labels: level1, gssoc-ext
