Repository GarimaSingh0109/Resum-Resume, pull requests merged in 2024-10, with the labels that each got.

#26 Issue #4 solved. Get Started Button is improved on Home page.
  index.html
Labels: gssoc-extd, hacktoberfeast, level1

#99 Fixes #11 Improved the overall text of the website
  global.css
  index.html
Labels: good first issue, hacktoberfest, level1, gssoc-ext, hacktoberfest-accepted

#96 Navbar Responsiveness
  about.html
  index.html
  resume.html
  style.css
Labels: hacktoberfest, level2, gssoc-ext, hacktoberfest-accepted

#178 Enhanced Resum Resume Project: Streamlined Design and Functionality
  .vscode/settings.json
  CONTRIBUTING.md
  Li.gif
  about.html
  assets/emily_johnson.jpg
  assets/instant resume.jpg
  assets/joao-ferrao-4YzrcDNcRVg-unsplash.jpg
  assets/john_smith.jpg
  assets/jondoe.jpg
  assets/securedata.jpg
  assets/support.jpg
  images/background-home.png
  images/favicon-removebg-preview.png
  index.html
  login.html
  readme.md
  resume.html
  script.js
  signup.html
  style.css
Labels: hacktoberfest, level3, gssoc-ext, hacktoberfest-accepted

#229 Add Scroll to top button
  index.html
Labels: hacktoberfest, level1, gssoc-ext, hacktoberfest-accepted

#182 Twitter logo fix
  login.html
Labels: hacktoberfest, level1, gssoc-ext, hacktoberfest-accepted

#183 Fix: Color Scheme and Text Sizing Improvements (#82)
  style.css
Labels: hacktoberfest, level1, gssoc-ext, hacktoberfest-accepted

#338 add website views widget
  index.html
Labels: hacktoberfest, level1, gssoc-ext, hacktoberfest-accepted

#225 added gsap and navbar design
  about.html
  index.html
  resume.html
  script.js
  style.css
Labels: hacktoberfest, gssoc-ext, hacktoberfest-accepted

#389 #385 Changed font styles in footer
  style.css
Labels: hacktoberfest, level1, gssoc-ext, hacktoberfest-accepted

#358 [FIX] Landing Page Error Fixed
  index.html
  style.css
Labels: hacktoberfest, level1, gssoc-ext, hacktoberfest-accepted

#507 Added a Resume Tips Section
  about.html
  index.html
  resume.html
  resume_tips.html
Labels: hacktoberfest, level3, gssoc-ext, hacktoberfest-accepted

#644 Update readme.md
  readme.md
Labels: hacktoberfest, level1, gssoc-ext, hacktoberfest-accepted

#226 Add mini chatbot to the website
  .env.example
  boy.png
  chatbot.gif
  chatbot.html
  index.html
Labels: hacktoberfest, level3, gssoc-ext, hacktoberfest-accepted

#723 Fixed CV Templates Footer Link Redirection
  cv.html
  galleryView.html
  index.html
Labels: hacktoberfest, level3, gssoc-ext, hacktoberfest-accepted

#491 This PR is related to Issue #489. privacypolicy.html has been added
  about.html
  index.html
  package-lock.json
  privacypolicy.html
  resume.html
  style.css
Labels: hacktoberfest, level2, gssoc-ext, hacktoberfest-accepted

#813 Homepage Repeated Content, UI Improvements, and Fixes
  index.html
Labels: hacktoberfest, level1, gssoc-ext, hacktoberfest-accepted

#854 Add Collapsible Categories with Dropdown for Step 1 in Resume Builder
  Resume.css
  Resume.js
  resume.html
  resume2.js
Labels: hacktoberfest, level3, gssoc-ext, hacktoberfest-accepted

#884 Implement Character Limit and Counter for Resume Template Inputs
  Resume.css
  Resume.js
  resume.html
  resume2.js
Labels: hacktoberfest, level3, gssoc-ext, hacktoberfest-accepted

#833 Improve Footer and Navbar Styling on About Page
  about.html
Labels: hacktoberfest, level2, gssoc-ext, hacktoberfest-accepted

#834 Add Feature to Download Resume as PDF
  Resume.js
Labels: hacktoberfest, level3, gssoc-ext, hacktoberfest-accepted

#898 I want to style login page
  login.css
  login.html
  login.js
Labels: hacktoberfest, level2, gssoc-ext, hacktoberfest-accepted

#883 made navbar responsive and consistent
  about.html
  index.html
  resume.html
  style.css
Labels: hacktoberfest, level1, gssoc-ext, hacktoberfest-accepted

#881 Add "Add Another" Button in Achievements and Certifications Section and Fix Data Reflection in Review and PDF
  Resume.css
  Resume.js
Labels: hacktoberfest, level3, gssoc-ext, hacktoberfest-accepted

#923 Added a contributing.md file
  CODE_OF_CONDUCT.md
  contributing.md
Labels: hacktoberfest, level1, gssoc-ext, hacktoberfest-accepted
